export WANDB_API_KEY="2f787b5e67ea6f6970182ba8f57f0a61060d7d12"

deepspeed train.py \
    --model_name_or_path google/gemma-2-9b-it \
    --model_max_length 2048 \
    --deepspeed ./scripts/zero2.json \
    --lora_enable True \
    --lora_r 16 \
    --lora_alpha 32 \
    --lora_target "[\"q_proj\", \"k_proj\", \"v_proj\", \"o_proj\", \"gate_proj\"]" \
    --output_dir "a100_gemma_template_with_token_num_eos_best_para" \
    --report_to "wandb" \
    --bf16 True \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --save_strategy "no" \
    --lr_scheduler_type "cosine" \
    --dataloader_num_workers 4 \
    --save_total_limit 1 \
    --save_steps 0.2 \
    --layers_to_transform 0 \
    --learning_rate 2e-4 \
    --warmup_steps 20 \
    --truncation_method right \
    --length_assign_method method_2 \
    --chat_template "template_with_token_num_eos"

deepspeed train.py \
    --model_name_or_path princeton-nlp/gemma-2-9b-it-SimPO \
    --model_max_length 2048 \
    --deepspeed ./scripts/zero2.json \
    --lora_enable True \
    --lora_r 16 \
    --lora_alpha 32 \
    --lora_target "[\"q_proj\", \"k_proj\", \"v_proj\", \"o_proj\", \"gate_proj\"]" \
    --output_dir "a100_gemma-2-9b-it-SimPO" \
    --report_to "wandb" \
    --bf16 True \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --save_strategy "no" \
    --lr_scheduler_type "cosine" \
    --dataloader_num_workers 4 \
    --save_total_limit 1 \
    --save_steps 0.2 \
    --layers_to_transform 0 \
    --learning_rate 2e-4 \
    --warmup_steps 20 \
    --truncation_method right \
    --length_assign_method method_2 \
    --chat_template "template_with_token_num_eos"

deepspeed train.py \
    --model_name_or_path google/gemma-2-9b-it \
    --model_max_length 2048 \
    --deepspeed ./scripts/zero3.json \
    --lora_enable False \
    --output_dir "a100_gemma_template_with_token_num_eos_FT_2e-5" \
    --report_to "wandb" \
    --bf16 True \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --save_strategy "no" \
    --lr_scheduler_type "cosine" \
    --dataloader_num_workers 4 \
    --save_total_limit 1 \
    --save_steps 0.2 \
    --layers_to_transform 0 \
    --learning_rate 2e-5 \
    --warmup_steps 20 \
    --truncation_method right \
    --length_assign_method method_2 \
    --chat_template "template_with_token_num_eos"

deepspeed train.py \
    --model_name_or_path google/gemma-2-9b-it \
    --model_max_length 2048 \
    --deepspeed ./scripts/zero3.json \
    --lora_enable False \
    --output_dir "a100_gemma_template_with_token_num_eos_FT_8e-5" \
    --report_to "wandb" \
    --bf16 True \
    --num_train_epochs 1 \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --save_strategy "no" \
    --lr_scheduler_type "cosine" \
    --dataloader_num_workers 4 \
    --save_total_limit 1 \
    --save_steps 0.2 \
    --layers_to_transform 0 \
    --learning_rate 8e-5 \
    --warmup_steps 20 \
    --truncation_method right \
    --length_assign_method method_2 \
    --chat_template "template_with_token_num_eos"
